# Generated by Django 4.1.2 on 2022-10-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='departament',
        ),
    ]
