# Generated by Django 4.1.2 on 2022-11-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_profile_departament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_end',
            field=models.DateTimeField(null=True, verbose_name='Дата выполнения'),
        ),
    ]
