# Generated by Django 4.1.2 on 2022-10-20 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_profile_departament'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='departament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.departament', verbose_name='Отдел'),
            preserve_default=False,
        ),
    ]
